[project]
name = "Brakeit"
version = "1.0"
description = "Get BrokenSource Monorepo easily"
authors = [{name="Tremeschin"}]
dependencies = [
    "pygit2",
    "poetry"
]

[tool.poetry]
name = "Brakeit"
version = "1.0"
description = "Get BrokenSource Monorepo easily"
authors = ["Tremeschin"]
